version: '3'

volumes: 
  data:
  config:
  db:

networks:
  nextcloud_network:


services:

  # Reverse-Proxy
  nginx: 
    image: nginx:latest
    container_name: nginx
    networks: 
      - nextcloud_network
    depends_on:
      - nextcloud
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/conf.d:/etc/nginx/conf.d
      - ./nginx/vhost.d:/etc/nginx/vhost.d
      - ./nginx/html:/etc/nginx/html
      #- ./nginx/certs:/etc/nginx/certs
    ports:
      - 80:80
      - 443:443
    restart: unless-stopped

  #Nextcloud DB
  mariadb:
    image: jsurf/rpi-mariadb:latest
    container_name: nextcloud-mariadb
    networks: 
      - nextcloud_network
    volumes: 
      - ./db:/var/lib/mysql
      - /etc/localtime:/etc/localtime:ro
    environment:
      - MYSQL_ROOT_PASSWORD=dummy
      - MYSQL_PASSWORD=dummy
      - MYSQL_DATABASE=dummy
      - MYSQL_USER=dummy
    restart: unless-stopped

  # Nextcloud
  nextcloud:
    image: nextcloud:latest
    container_name: nextcloud
    networks: 
      - nextcloud_network
    depends_on:
      - mariadb
      #- letsencrypt
    volumes: 
      - ./nextcloud:/var/www/html
      - ./nextcloud/apps:/var/www/html/apps  #redundant?
      - ./config:/var/www/html/config
      - ./data:/var/www/html/data
      - ./nextcloud/themes:/var/www/html/themes
      - ./nextcloud/custom_apps:/var/www/html/custom_apps  #redundant?
      - ./apache2.conf:/etc/apache2/apache2.conf
    environment: 
      - VIRTUAL_HOST=nextcloud.YOUR-DOMAIN
      #- LETSENCRYPT_HOST=nextcloud.YOUR-DOMAIN
      #- LETSENCRYPT_EMAIL=YOUR-EMAIL
    build:
      context: ./nextcloud
    ports:
      - 8080:80
    restart: unless-stopped



  # LetsEncrypt
  # letsencrypt:
  #   image:


  # Web App
  # webapp:
  #   image:
  #   container_name:
  #   depends:on:
  #     - nginx
  #   build:
  #     context: ./web-app
  #   ports:
  #     - 1234:1234
  #   restart: 